forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-mysql', '~> 2.3.0'
#mod 'puppetlabs-stdlib', '~> 4.4.0'
mod 'puppetlabs-concat', '~> 1.2.0'
mod 'puppetlabs-mongodb', '0.17.0'
mod 'puppet-archive', '~> 0.4.4'
mod 'puppetlabs-vcsrepo', '~> 1.4.0'
mod 'fsalum-redis', '~> 1.0.3'
mod 'elliotblackburn-nodeapp',
  :path => 'site-modules/nodeapp'